"""
CampusGrid AI: Optimization Domain Entities
Pydantic domain entities for 48-period dispatch optimization and cost metrics.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class OptimizationInput(BaseModel):
    """Parameters passed to the MILP dispatch solver."""
    time_slots: List[str]
    base_load_kw: List[float]
    solar_gen_kw: List[float]
    grid_tariff_lkr_kwh: List[float]
    battery_capacity_kwh: float = Field(default=500.0, gt=0)
    max_charge_rate_kw: float = Field(default=100.0, gt=0)
    max_discharge_rate_kw: float = Field(default=100.0, gt=0)
    initial_soc_ratio: float = Field(default=0.50, ge=0.20, le=0.90)
    min_soc_ratio: float = Field(default=0.20, ge=0.0, le=1.0)
    max_soc_ratio: float = Field(default=0.90, ge=0.0, le=1.0)
    round_trip_efficiency: float = Field(default=0.92, gt=0.0, le=1.0)
    peak_demand_penalty_lkr_kva: float = Field(default=1100.0, description="Monthly peak surcharge")
    max_grid_import_kw: Optional[float] = Field(default=None, description="Maximum utility grid interconnect capacity in kW")
    tier0_load_kw: Optional[List[float]] = Field(default=None, description="Non-curtailable critical load profile (kW)")
    tier1_load_kw: Optional[List[float]] = Field(default=None, description="Temperature-flexible load profile (kW)")
    tier2_load_kw: Optional[List[float]] = Field(default=None, description="Curtailable/shiftable load profile (kW)")

class BindingConstraint(BaseModel):
    """Represents an active limit restricting the optimal solution."""
    name: str
    time_slot: Optional[str] = None
    threshold: float
    actual_value: float
    economic_impact_lkr: Optional[float] = None

class OptimizationResult(BaseModel):
    """Output generated by the deterministic MILP solver."""
    time_slots: List[str]
    optimized_grid_kw: List[float]
    battery_charge_kw: List[float]
    battery_discharge_kw: List[float]
    battery_soc_kwh: List[float]
    baseline_cost_lkr: float
    optimized_cost_lkr: float
    net_savings_lkr: float
    savings_percentage: float
    peak_demand_baseline_kw: float
    peak_demand_optimized_kw: float
    solver_status: str = "Optimal"
    solve_time_ms: float = 0.0
    binding_constraints: List[BindingConstraint] = Field(default_factory=list)
