"""
CampusGrid AI: Optimization Domain Entities
Pydantic domain entities for 48-period dispatch optimization and cost metrics.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class OptimizationInput(BaseModel):
    """Parameters passed to the MILP dispatch solver."""
    time_slots: List[str]
    base_load_kw: List[float]
    solar_gen_kw: List[float]
    grid_tariff_lkr_kwh: List[float]
    battery_capacity_kwh: float = Field(default=500.0, gt=0)
    max_charge_rate_kw: float = Field(default=100.0, gt=0)
    max_discharge_rate_kw: float = Field(default=100.0, gt=0)
    initial_soc_ratio: float = Field(default=0.50, ge=0.20, le=0.90)
    min_soc_ratio: float = Field(default=0.20, ge=0.0, le=1.0)
    max_soc_ratio: float = Field(default=0.90, ge=0.0, le=1.0)
    round_trip_efficiency: float = Field(default=0.92, gt=0.0, le=1.0)
    peak_demand_penalty_lkr_kva: float = Field(default=1100.0, description="Monthly peak surcharge")
    max_grid_import_kw: Optional[float] = Field(default=None, description="Maximum utility grid interconnect capacity in kW")
    # Load tiers. When given, the three profiles partition base_load_kw interval by interval
    # (tier0 + tier1 + tier2 == base_load_kw) and the solver enforces them:
    #   Tier 0 is a fixed term in the power balance, so it can never be curtailed;
    #   Tier 1 (air-conditioning) may move by at most tier1_max_reduction_ratio per interval and
    #          must use the same energy over the day (pre-cool before the peak, recover after);
    #   Tier 2 (pumps, EV chargers, ornamental lighting) may be moved to any interval, at no more
    #          than tier2_max_kw, again with the same daily energy.
    tier0_load_kw: Optional[List[float]] = Field(default=None, description="Non-curtailable critical load profile (kW)")
    tier1_load_kw: Optional[List[float]] = Field(default=None, description="Temperature-flexible load profile (kW)")
    tier2_load_kw: Optional[List[float]] = Field(default=None, description="Curtailable/shiftable load profile (kW)")
    tier1_max_reduction_ratio: float = Field(default=0.0, ge=0.0, le=0.5, description="Largest per-interval Tier-1 change, as a fraction")
    tier2_max_kw: Optional[float] = Field(default=None, gt=0, description="Rated power of the shiftable Tier-2 equipment; defaults to its profile's peak")
    # Demand charge. PUCSL bills the month's highest demand in kVA; kVA = kW / power factor.
    power_factor: float = Field(default=1.0, gt=0.5, le=1.0, description="Site power factor (kW -> kVA)")
    month_to_date_peak_kva: Optional[float] = Field(
        default=None, ge=0,
        description="Highest demand already recorded this billing month (e.g. from the CEB bill or meter). When "
                    "given, the plan pays the full monthly rate only on demand above it; otherwise 1/30 of the "
                    "monthly charge is attributed to the day's peak.",
    )

class BindingConstraint(BaseModel):
    """Represents an active limit restricting the optimal solution."""
    name: str
    time_slot: Optional[str] = None
    threshold: float
    actual_value: float
    economic_impact_lkr: Optional[float] = None

class OptimizationResult(BaseModel):
    """Output generated by the deterministic MILP solver.

    Cost figures are per day. Solvers that price the peak report baseline/optimized cost as
    energy cost plus the demand charge attributed to the day (see demand_charge_basis: the
    daily 1/30 share, or the increase over the month-to-date peak), with the split in the
    optional breakdown fields below (None when a solver does not report it).
    """
    time_slots: List[str]
    optimized_grid_kw: List[float]
    battery_charge_kw: List[float]
    battery_discharge_kw: List[float]
    battery_soc_kwh: List[float]
    baseline_cost_lkr: float
    optimized_cost_lkr: float
    net_savings_lkr: float
    savings_percentage: float
    energy_savings_lkr: Optional[float] = None
    demand_charge_savings_lkr: Optional[float] = Field(
        default=None, description="Demand charge saved by lowering the peak, on the basis in demand_charge_basis"
    )
    peak_demand_baseline_kw: float
    peak_demand_optimized_kw: float
    solver_status: str = "Optimal"
    solve_time_ms: float = 0.0
    binding_constraints: List[BindingConstraint] = Field(default_factory=list)
    # Present only when the input carried load tiers.
    served_tier0_kw: Optional[List[float]] = None
    served_tier1_kw: Optional[List[float]] = None
    served_tier2_kw: Optional[List[float]] = None
    demand_charge_basis: Optional[str] = None
    post_solve_checks: Optional[Dict[str, Any]] = None
