"""
CampusGrid AI: Agent 2 — Grey-Box Physics Constant Calibration
Module Owner: Member 3 (Digital Twin, Cyber-Physical Physics & Simulation)

The 2R2C model in `thermal_model.py` shipped with GUESSED constants (c_in=50.0 kWh/°C,
r_vent=2.5 °C/kW) — building-scale numbers that give a single lecture hall a thermal
time constant of days. This module fits both constants for a real-sized room against
measured indoor temperatures using `scipy.optimize.least_squares`, and reports how much
more accurate the fitted model is than the guessed one — Developer 2's headline result.
The room's structure constants (c_wall, r_in, r_out) are held at their per-seat
estimates from room_presets.py during the fit; only c_in and r_vent are fitted.

Real building-management-system logs are not yet wired into the project (Developer 1
owns telemetry ingestion, and no live campus deployment exists for a coursework
project). Until that feed exists, `generate_synthetic_reference_dataset()` stands in
for one: a 180-seat lecture hall with a KNOWN "true" (c_in, r_vent), occupied during
weekday operating hours, sunlit through its windows on a typical day, its HVAC power
logged from a thermostat holding 24 °C — the shape a real BMS export has — plus Gaussian
sensor noise. The fit is told the same solar gain, as it would be told a real hall's
(from its window area and a pyranometer or the clear-sky model in solar.py). Fitting against it proves the
pipeline recovers the physics and gives an honest, reproducible "how much better than
guessing" number. Swapping in real sensor readings later needs no change to
`fit_thermal_constants()`, only different inputs.

The fitted values feed room_presets.py's Lecture Hall preset; a unit test keeps the two
in step.
"""

import csv
import os
import random
from dataclasses import dataclass
from datetime import date
from typing import List, Optional, Tuple

import numpy as np
from scipy.optimize import least_squares

from src.agents.digital_twin.thermal_model import BuildingThermalTwin
from src.agents.digital_twin.operating_hours import occupied_mask, operating_hours_for
from src.agents.digital_twin.room_presets import ROOM_TYPE_PRESETS, AC_UNIT_COOLING_KW
from src.agents.digital_twin.solar import solar_heat_gain_kw, typical_irradiance_kw_m2

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SEED_CSV_PATH = os.path.join(_REPO_ROOT, "backend", "data", "seeds", "sample_campus_seed.csv")

GUESSED_C_IN = 50.0
GUESSED_R_VENT = 2.5
_LOG_STEP = 0.02  # finite-difference step in log-space: a 2% change in a constant
_FIT_STARTS = 3   # least-squares refinements, from the best grid points

CALIBRATION_SEATS = 180
# The synthetic stand-in for the real hall: what a BMS log would be generated by.
TRUE_C_IN = 1.33      # kWh/°C
TRUE_R_VENT = 0.745   # °C/kW
CALIBRATION_AC_UNITS = 5
THERMOSTAT_SETPOINT_C = 24.0
CALIBRATION_DATE = date(2026, 10, 1)  # a weekday

_hall = ROOM_TYPE_PRESETS["lecture_hall"]
# Structure constants for the calibration room — estimated, held fixed during the fit.
HALL_C_WALL = round(_hall.c_wall_per_seat * CALIBRATION_SEATS, 4)
HALL_R_IN = round(1.0 / (_hall.g_in_per_seat * CALIBRATION_SEATS), 5)
HALL_R_OUT = round(1.0 / (_hall.g_out_per_seat * CALIBRATION_SEATS), 5)
HALL_SOLAR_APERTURE_M2 = round(_hall.solar_aperture_m2_per_seat * CALIBRATION_SEATS, 3)


def calibration_solar_gain_kw(n_intervals: int = 48) -> List[float]:
    """Q_solar on the calibration hall across the calibration day (kW per interval)."""
    return solar_heat_gain_kw(typical_irradiance_kw_m2(CALIBRATION_DATE, n_intervals), HALL_SOLAR_APERTURE_M2)


def load_ambient_temperatures(csv_path: str = SEED_CSV_PATH) -> List[float]:
    """Reads the 48 real half-hourly outdoor temperatures from the campus seed data."""
    ambient_temps: List[float] = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            ambient_temps.append(float(row["outdoor_temp_c"]))
    return ambient_temps


def _hall_twin(c_in: float, r_vent: float) -> BuildingThermalTwin:
    return BuildingThermalTwin(c_in=c_in, r_vent=r_vent, c_wall=HALL_C_WALL, r_in=HALL_R_IN, r_out=HALL_R_OUT)


def generate_synthetic_reference_dataset(
    true_c_in: float = TRUE_C_IN,
    true_r_vent: float = TRUE_R_VENT,
    noise_std_c: float = 0.05,
    initial_temp_c: float = 24.0,
    seed: int = 42,
) -> Tuple[List[float], List[int], List[float], List[float]]:
    """A labelled calibration dataset with a KNOWN ground truth, standing in for a real
    BMS export. Returns (ambient_temps, occupant_counts, hvac_power_kw, measured_temps)."""
    # Imported here: the agent module depends on room_presets, which this module feeds.
    from src.agents.digital_twin.agent import DigitalTwinAgent

    ambient_temps = load_ambient_temperatures()
    mask = occupied_mask(operating_hours_for(CALIBRATION_DATE), len(ambient_temps))
    occupant_counts = [CALIBRATION_SEATS if open_ else 0 for open_ in mask]

    true_twin = _hall_twin(true_c_in, true_r_vent)
    run = DigitalTwinAgent(
        thermal_twin=true_twin, hvac_max_cooling_kw=CALIBRATION_AC_UNITS * AC_UNIT_COOLING_KW,
    ).execute({
        "initial_temp_c": initial_temp_c,
        "ambient_temperatures_c": ambient_temps,
        "occupancy_counts": occupant_counts,
        "occupied_mask": mask,
        "target_setpoint_c": THERMOSTAT_SETPOINT_C,
        "solar_gain_kw": calibration_solar_gain_kw(len(ambient_temps)),
    })
    if not run.success:
        raise RuntimeError(f"Could not generate the calibration dataset: {run.error}")
    hvac_power_kw = run.data["hvac_power_kw"]
    clean_temps = run.data["simulated_indoor_temps_c"]

    rng = random.Random(seed)
    measured_temps = [round(t + rng.gauss(0.0, noise_std_c), 2) for t in clean_temps]
    return ambient_temps, occupant_counts, hvac_power_kw, measured_temps


@dataclass
class CalibrationResult:
    fitted_c_in: float
    fitted_r_vent: float
    guessed_c_in: float
    guessed_r_vent: float
    rmse_guessed: float
    rmse_fitted: float

    @property
    def accuracy_improvement_pct(self) -> float:
        if self.rmse_guessed == 0:
            return 0.0
        return round(100.0 * (self.rmse_guessed - self.rmse_fitted) / self.rmse_guessed, 1)


def _rmse(predicted: List[float], measured: List[float]) -> float:
    predicted_arr = np.asarray(predicted, dtype=float)
    measured_arr = np.asarray(measured, dtype=float)
    return float(np.sqrt(np.mean((predicted_arr - measured_arr) ** 2)))


def fit_thermal_constants(
    initial_temp_c: float,
    ambient_temps: List[float],
    occupant_counts: List[int],
    hvac_power_kw: List[float],
    measured_indoor_temps_c: List[float],
    initial_guess: Tuple[float, float] = (GUESSED_C_IN, GUESSED_R_VENT),
    solar_gain_kw: Optional[List[float]] = None,
) -> CalibrationResult:
    """Fits (c_in, r_vent) against `measured_indoor_temps_c` with
    `scipy.optimize.least_squares`, and reports the accuracy gain over the guess.
    `solar_gain_kw` is the room's known Q_solar per interval (none if omitted)."""

    def simulate(c_in: float, r_vent: float) -> List[float]:
        return _hall_twin(c_in, r_vent).simulate(
            initial_temp_c=initial_temp_c,
            ambient_temps=ambient_temps,
            occupant_counts=occupant_counts,
            hvac_power_kw=hvac_power_kw,
            solar_gain_kw=solar_gain_kw,
        )

    # Fitted in log-space: the guess is ~40x off and the two constants sit an order of
    # magnitude apart, which leaves a raw-unit fit so badly conditioned it wanders the
    # wrong way. Log-parameters make every step a relative change and keep both positive.
    def residuals(log_params: np.ndarray) -> np.ndarray:
        c_in, r_vent = np.exp(log_params)
        return np.asarray(simulate(c_in, r_vent), dtype=float) - np.asarray(measured_indoor_temps_c, dtype=float)

    # A 40x-off guess is not a safe starting point: from it the landscape slopes towards a
    # false minimum (an ever-heavier room that barely reacts). A log-spaced grid — plus the
    # guess itself — picks the starts, and least-squares refines from the best few. With
    # solar gain in the data the valley is narrow in r_vent, so one start can stall on its
    # wall; the best of several refinements is kept.
    grid = [np.log(initial_guess)] + [
        np.log([c, r]) for c in np.logspace(-1, 2, 7) for r in np.logspace(-1, 1, 13)
    ]
    starts = sorted(grid, key=lambda p: float(np.sum(residuals(p) ** 2)))[:_FIT_STARTS]

    # `simulate()` reports temperatures at 2-decimal sensor precision, so the Jacobian's
    # finite-difference step must be large enough to move the output past that floor or
    # the gradient reads as exactly zero and the fit "converges" where it started. scipy's
    # own `diff_step` is relative to the parameter — in log-space a constant near 1 is a
    # parameter near 0, where that step collapses to ~1e-8. So the Jacobian is supplied
    # with a fixed log-step: a 2% change in each physical constant.
    def jacobian(log_params: np.ndarray) -> np.ndarray:
        base = residuals(log_params)
        jac = np.empty((base.size, log_params.size))
        for k in range(log_params.size):
            step = np.zeros_like(log_params)
            step[k] = _LOG_STEP
            jac[:, k] = (residuals(log_params + step) - base) / _LOG_STEP
        return jac

    fits = [least_squares(residuals, x0=np.asarray(s, dtype=float), jac=jacobian) for s in starts]
    result = min(fits, key=lambda f: f.cost)
    fitted_c_in, fitted_r_vent = np.exp(result.x)

    return CalibrationResult(
        fitted_c_in=round(float(fitted_c_in), 4),
        fitted_r_vent=round(float(fitted_r_vent), 4),
        guessed_c_in=initial_guess[0],
        guessed_r_vent=initial_guess[1],
        rmse_guessed=round(_rmse(simulate(*initial_guess), measured_indoor_temps_c), 4),
        rmse_fitted=round(_rmse(simulate(fitted_c_in, fitted_r_vent), measured_indoor_temps_c), 4),
    )


def run_calibration_report() -> CalibrationResult:
    """Builds the synthetic reference dataset and fits against it. Run with
    `python -m src.agents.digital_twin.thermal_calibration` for the report used in the
    coursework write-up and viva."""
    ambient_temps, occupant_counts, hvac_power_kw, measured_temps = generate_synthetic_reference_dataset()
    return fit_thermal_constants(
        initial_temp_c=24.0,
        ambient_temps=ambient_temps,
        occupant_counts=occupant_counts,
        hvac_power_kw=hvac_power_kw,
        measured_indoor_temps_c=measured_temps,
        solar_gain_kw=calibration_solar_gain_kw(len(ambient_temps)),
    )


if __name__ == "__main__":
    report = run_calibration_report()
    print(f"Room: {CALIBRATION_SEATS}-seat lecture hall (true c_in={TRUE_C_IN}, r_vent={TRUE_R_VENT})")
    print("Guessed constants:  c_in={:.2f} kWh/°C, r_vent={:.2f} °C/kW -> RMSE={:.4f} °C".format(
        report.guessed_c_in, report.guessed_r_vent, report.rmse_guessed
    ))
    print("Fitted constants:   c_in={:.4f} kWh/°C, r_vent={:.4f} °C/kW -> RMSE={:.4f} °C".format(
        report.fitted_c_in, report.fitted_r_vent, report.rmse_fitted
    ))
    print("Accuracy improvement: {:.1f}%".format(report.accuracy_improvement_pct))
