"""
CampusGrid AI: Optimization Contract Models
Defines Pydantic schemas for dispatch optimization inputs and solver outputs.
"""

from typing import List
from pydantic import BaseModel, Field

class OptimizationRequest(BaseModel):
    """Parameters passed to the MILP dispatch solver."""
    battery_capacity_kwh: float = Field(default=500.0, gt=0, description="Total battery capacity in kWh")
    max_charge_rate_kw: float = Field(default=100.0, gt=0, description="Max battery charge rate in kW")
    max_discharge_rate_kw: float = Field(default=100.0, gt=0, description="Max battery discharge rate in kW")
    initial_soc_ratio: float = Field(default=0.50, ge=0.20, le=0.90, description="Starting battery State-of-Charge")

class OptimizationResult(BaseModel):
    """Output generated by the MILP solver."""
    time_slots: List[str]
    optimized_grid_kw: List[float]
    battery_charge_kw: List[float]
    battery_discharge_kw: List[float]
    battery_soc_kwh: List[float]
    baseline_cost_lkr: float
    optimized_cost_lkr: float
    net_savings_lkr: float
    savings_percentage: float
